Add PDLL example (#9406)
* try on pdll.
some erros:
1. mlir-pdll -h error
2. cmake circular dependency.
3. error: ‘parseSourceString’ is not a member of ‘mlir’.

* fix

* try on pdll.

* add a pass for pdll.

* generate cpp by pdll

* generate cpp by pdll.

* generate cpp by pdll.

* generate cpp by pdll.

* refine

* refine

* refine

* fix

* rm old pass

* fix

* fuse bias_add and dropout

* add file check

* fix

* match more attributes

* refine

* fix

* fix

* fix axis

* fix seed

* dirty fix

* fix

* refactor

* fix

* refine

* refine

* fix

* refine

* rm unused

* refine filecheck

* refine

* refine

* rm old impl

* rename pattern cpp files

* auto format by CI

* refine

* refine

* refine

* refine

* simplify

* refine

* refine

* fix typo

Co-authored-by: jackalcooper <jackalcooper@gmail.com>
Co-authored-by: oneflow-ci-bot <ci-bot@oneflow.org>