Fix build error with gcc 12 for oneTBB (#10236)
The build process will not succeed with GCC 12 or later versions (such
as 13) because of a compile error in oneTBB.
```
In file included from /usr/include/c++/12.2.0/atomic:41,
                 from /home/twice/project/oneflow2/build/_deps/tbb-src/src/tbb/../../include/oneapi/tbb/detail/_utils.h:22,
                 from /home/twice/project/oneflow2/build/_deps/tbb-src/src/tbb/address_waiter.cpp:17:
In member function 'void std::__atomic_base<_IntTp>::store(__int_type, std::memory_order) [with _ITp = bool]',
    inlined from 'void std::atomic<bool>::store(bool, std::memory_order)' at /usr/include/c++/12.2.0/atomic:104:20,
    inlined from 'void tbb::detail::r1::concurrent_monitor_base<Context>::abort_all_relaxed() [with Context = tbb::detail::r1::address_context]' at /home/twice/project/oneflow2/build/_deps/tbb-src/src/tbb/concurrent_monitor.h:430:53,
    inlined from 'void tbb::detail::r1::concurrent_monitor_base<Context>::abort_all() [with Context = tbb::detail::r1::address_context]' at /home/twice/project/oneflow2/build/_deps/tbb-src/src/tbb/concurrent_monitor.h:413:26,
    inlined from 'void tbb::detail::r1::concurrent_monitor_base<Context>::destroy() [with Context = tbb::detail::r1::address_context]' at /home/twice/project/oneflow2/build/_deps/tbb-src/src/tbb/concurrent_monitor.h:446:24,
    inlined from 'void tbb::detail::r1::clear_address_waiter_table()' at /home/twice/project/oneflow2/build/_deps/tbb-src/src/tbb/address_waiter.cpp:60:40:
/usr/include/c++/12.2.0/bits/atomic_base.h:464:25: error: 'void __atomic_store_1(volatile void*, unsigned char, int)' writing 1 byte into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  464 |         __atomic_store_n(&_M_i, __i, int(__m));
      |         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
```

Refer to https://github.com/oneapi-src/oneTBB/issues/843, we can
workaround this issue by adding `-Wno-error=stringop-overflow` to
compiler flags.