Fix handle_size_arg when len(size) == 0 (#9975)
修复两个问题：
## flow.full
```
>>> import oneflow as flow
>>> flow.full([], 8)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/home/pangguojian/oneflow/python/oneflow/nn/modules/constant.py", line 396, in full_op
    size = _handle_size_arg(size)
  File "/data/home/pangguojian/oneflow/python/oneflow/nn/modules/utils.py", line 50, in _handle_size_arg
    assert len(size) > 0, "size of tensor doesn't exists"
AssertionError: size of tensor doesn't exists
```
torch中：
```
# torch.full
>>> import torch
>>> torch.full([],8)
tensor(8)
```
修改方法当len(size)==0时直接返回size

## new_full
在torch中：
```
>>> import torch
>>> tensor = torch.ones((2,))
>>> tensor.new_full([], 2)
tensor(2.)
```
oneflow中：
```
>>> import oneflow as flow
>>> tensor = flow.ones((2,))
>>> tensor.new_full([], 8)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/home/pangguojian/oneflow/python/oneflow/framework/tensor.py", line 210, in _new_full
    return flow.new_full(
  File "/data/home/pangguojian/oneflow/python/oneflow/nn/modules/constant.py", line 531, in new_full_op
    size = _handle_size_arg(size)
  File "/data/home/pangguojian/oneflow/python/oneflow/nn/modules/utils.py", line 50, in _handle_size_arg
    assert len(size) > 0, "size of tensor doesn't exists"
AssertionError: size of tensor doesn't exists
```
应用问题一的修改后，问题变为：
```
>>> import oneflow as flow
>>> tensor = flow.ones((2,))
>>> tensor.new_full([], 2)
tensor([2., 2.], dtype=oneflow.float32)
```
这是由于`_handle_meta_args`中
```
if size is None or len(size) == 0:
        new_size = input.shape
```
所以返回的new_size是shape，导致了不一致

---------

Co-authored-by: Zipeng Xie <53039617+xiezipeng-ML@users.noreply.github.com>